version: 2
jobs:
  execute-suite:
    docker:
      - image: ghostinspector/test-runner-node
    steps:
      - checkout
      - run:
          name: Run Suite
          command: |
            /bin/runghostinspectorsuite test-app/index.js --myCliVar=my-cli-var
          environment:
            - APP_PORT: 8000
            - GI_SUITE: 5a9ebeab9d311c32b43f3f5d
            - MY_ENV_VAR: my-env-var

workflows:
  version: 2
  test_base_image:
    jobs:
      - execute-suite