version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build test-runner-node:$TAG
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            cp -R ./includes/ ./test-runner-node/includes
            docker build -t ghostinspector/test-runner-node:$TAG ./test-runner-node

workflows:
  version: 2
  test_base_image:
    jobs:
      - build