version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build test-runner-node
          command: |
            cp -R ./includes/ ./test-runner-node/includes
            docker build -t ghostinspector/test-runner-node:0.1.$CIRCLE_BUILD_NUM ./test-runner-node
      - run:
          name: Build test-app image
          command: |
            docker build -t test-app:0.1.$CIRCLE_BUILD_NUM ./test-app
      - run:
          name: Execute test
          command: |
            docker run \
              -e NGROK_TOKEN=$NGROK_TOKEN \
              -e GI_API_KEY=$GI_API_KEY \
              -e GI_SUITE=5a9ebeab9d311c32b43f3f5d \
              -e APP_PORT=8000 \
              -e MY_ENV_VAR=my-env-var \
              test-app:0.1.$CIRCLE_BUILD_NUM
      - run:
        name: Push new ghostinspector/test-runner-node image to Docker Hub
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ghostinspector/test-runner-node:0.1.$CIRCLE_BUILD_NUM
workflows:
  version: 2
  test_base_image:
    jobs:
      - build