version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build test-runner-node:$TAG
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            cp -R ./includes/ ./test-runner-node/includes
            docker build -t ghostinspector/test-runner-node:$TAG ./test-runner-node
  test:
    docker:
      - image: ghostinspector/test-runner-node:0.1.$CIRCLE_BUILD_NUM
    steps:
      - checkout
      - run:
          name: Run Suite
          command: |
            /bin/runghostinspectorsuite test-app/index.js --myCliVar=my-cli-var
          environment:
            - APP_PORT: 8000
            - GI_SUITE: 5a9ebeab9d311c32b43f3f5d
            - MY_ENV_VAR: my-env-var
workflows:
  version: 2
  test_base_image:
    jobs:
      - build
      - test